### ISSUE TITLE
The README *still* could be ambiguous.

### ISSUE THREAD

**Issue by ParkinT** [evancz/start-app#23]
When I follow the README, after pasting the code into Elm's Online Editor the next logical step is to try this code locally.  So, *completely naively*, I would:

1. install elm
1. create a `.elm` file (startapp.elm?)
1. call `elm make startapp.elm --output index.html`

It does not explain that the dependencies for `Html` and for `start-app` must be satisfied.

> I recommend a comment that a call to `elm-package install evancz/elm-html` and `elm-package install start-app --yes` is required if you want to use this sample code once you have installed Elm locally.

**Comment by JHKennedy4** [comment]
agreed, ideally, start-app should run out of the box without any need for configuration. I'm still unclear on naming conventions for packages, so even friendly error messages like the following don't help me much.

Simply including the appropriate dependencies in the elm-package.json by default would alleviate some of these difficulties by allowing someone to simply run `elm-package install`. I only say some because I'm running El Capitan and also had to build from source to install packages :)

```
Error when searching for modules imported by module 'StartApp':
    Could not find module 'Effects'

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

**Comment by JHKennedy4** [comment]
To add to this issue, the example code does not seem to actually do anything and I'm having trouble differentiating StartApp.elm and Simple.elm. The comments on each seem to indicate that they are different versions of the same functionality, but since neither seem to produce anything as output, it's difficult to figure out where I should actually start. Something that seems to be missing from Elm's overall documentation is a strong correlation between code and output, with helpful feedback along the way.

I've yet to find clear workflow documentation, and have had to piece together bits and pieces from each package of the Elm Platform's individual (and limited) documentation.

I definitely understand that this is a small community and you are likely spread fairly thin, just thought I would share the feedback. I'm hoping that once I get this pieced together and have a better grasp of how it all works together I'll be able to share what works for me.

**Comment by jvoigtlaender** [comment]
@JHKennedy4, what does "the example code does not seem to actually do anything" mean exactly? Is this a problem for you in the online editor or locally? What happens on screen (in browser) when you run the example?

About "clear workflow documentation", do you mind checking out the text from [here](https://github.com/elm-lang/elm-lang.org/pull/370/files#diff-015471f8a6a2652b9ce3365cfb826b4fR21) to [here](https://github.com/elm-lang/elm-lang.org/pull/370/files#diff-015471f8a6a2652b9ce3365cfb826b4fR149) and commenting on whether that would have helped you to find your way more easily?

**Comment by JHKennedy4** [comment]
Working locally and not seeing anything on the screen.

Both of those docs are extremely helpful for providing context. If you are
looking for an example of extremely good intro documentation, I highly
recommend the Phoenix Framework docs.

My main struggle thus far has been finding a clear path to basic production
style use where I can either incorporate elm into an existing project or
start a new project with a server side component.

For example, I'm still not clear what options are available on elm make and
what the difference between them is.

**Comment by jvoigtlaender** [comment]
Sorry, I'm afraid there is still not enough information to see what is the problem at your end. The example itself is correct. So, what did you do locally? Compiled to .html? Running in elm-reactor? Maybe you can post a sequence of commands you have run, starting in an empty directory, and what you clicked in elm-reactor (if you did use it).

About "workflow leading to production use", the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss) may be the best forum to get suggestions.

**Comment by JHKennedy4** [comment]
I used elm make to output a JavaScript file which failed to load for
unknown reasons (could have nothing to do with elm) and then tried elm
reactor where I navigated to each elm file in turn. Neither resulted in
output to the screen. Reading the code, it's not clear how they would, but
that might be my own ignorance.

What I would prefer is for the README to contain a clear set of commands I
should run to get started using this project.

**Comment by jvoigtlaender** [comment]
Let's try the following commands (if they work for you, this info could be some that is fit for the README):
* make a new directory
* change into that directory
* create a file called `Example.elm`, and into it put the code block from the current README
* on the command line, run `elm-package install evancz/start-app --yes`
* now *either*:
  - on the command line, run `elm-make Example.elm --output=Example.html`, then open `Example.html` in a browser, *or*
  - on the command line, run `elm-reactor`, then open `http://localhost:8000/Example.elm` in a browser

**Comment by JHKennedy4** [comment]
Sorry for the delay, haven't had time to play around for a few days. Those instructions did the trick, and are not something that would have ever occurred to to me to do having read the docs.

If you merge https://github.com/evancz/start-app/pull/27 someone already put together a PR with the instructions included.

**Comment by jvoigtlaender** [comment]
Have you seen the following page newly added to the Elm website?

http://elm-lang.org/get-started

Would the "Tools" section of that page have helped you here?

Let's assume that section becomes "required reading" for everyone having installed Elm. (It is already pointed to by the Windows/Mac/npm installers. And https://github.com/elm-lang/elm-lang.org/pull/326 and https://github.com/elm-lang/elm-platform/pull/84 intend to make it even more visible.)

Would you still have needed my [instructions](https://github.com/evancz/start-app/issues/23#issuecomment-140516938) above?

It might still make sense to merge something like #27 in this specific repository here, given that `start-app` might be a frequent entry point to Elm other than the website. But in general, I think it makes more sense to have people read http://elm-lang.org/get-started once instead of adding specific Elm tool usage instructions to every package on http://package.elm-lang.org/.

**Comment by leozdgao** [comment]
@jvoigtlaender Your instructions seems not work for me. I get this:

```
Error when searching for modules imported by module 'Main':
    Could not find module 'Html'

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

I'm sure elm-html has been installed, I can find it in elm-stuff/packages/evancz/elm-html. My platform is Win10 and Elm 0.15.1.

By the way, I feel Elm is hard for me to get started, I can't find the direct link to get-started page on the index page or the docs page, it's confusing. And I finally get http://elm-lang.org/get-started from here.

**Comment by jvoigtlaender** [comment]
Yeah, I also wish http://elm-lang.org/get-started were pointed out more prominently from the website. I have more than one pull request open to that effect.

About the Edit to your comment: Good that you got it working. The fact that you have to explicitly declare `evancz/elm-html` as a dependency (if you are going to use stuff from it directly), even though it is already installed as a transitive dependency of `start-app`, shouldn't be *that* surprising. It seems to be a common property of package managers and build tools in many languages. For example, it's the same for `cabal` in Haskell: If your project uses packages `A` and `B`, and `A` also uses `B` internally, you cannot simply only declare `A` as a dependency of your project. Among various reasons, this would not lead to a maintainable situation. For example, what if the implementation of `A` later changes and does not anymore depend on `B`? Then `B` would "disappear" even though your project still depends on it.

**Comment by leozdgao** [comment]
@jvoigtlaender You do make more sense. I commonly use `npm`, and the directory hierarchy of denpendencies of those two have some distinctions, I think I figured it out, thx. :smile:

**Comment by KayEss** [comment]
What I did was to go to the Elm home page and then follow the HTML app link. The README has a sample program which is kind of informative in a way, but not a single instruction as to how I can actually build it and run it.

It'd be really cool if this repository contained all the bits needed to do this -- the .elm file, whatever configuration is needed in elm-package.json (I'm getting an error about the Html import that I'm now going to have to try to find docs for) and a sample build command.

**Comment by fellz** [comment]
@evancz 
Definitly should be added to README, spent half an hour to understand how to make things work

```
Let's try the following commands (if they work for you, this info could be some that is fit for the README):

make a new directory
change into that directory
create a file called Example.elm, and into it put the code block from the current README
on the command line, run elm-package install evancz/start-app --yes
now either:
on the command line, run elm-make Example.elm --output=Example.html, then open Example.html in a browser, or
on the command line, run elm-reactor, then open http://localhost:8000/Example.elm in a browser
```

**Comment by jvoigtlaender** [comment]
@fellz, would #27 have addressed your case?

**Comment by fellz** [comment]
http://elm-lang.org/get-started ? and what to do with README for StartApp leave for confusion ? i can create pull request if you can't add this for some reasons...

**Comment by jvoigtlaender** [comment]
I can't, because I have no write access to this repository. I do think that adding http://elm-lang.org/get-started (or the information contained in its first half) to the README here would be useful. Whether that be via https://github.com/evancz/start-app/pull/27 or via a new pull request. But it's @evancz who needs to make a decision about merging.

**Comment by KayEss** [comment]
#27 seems like it'd be a great start. A link to the get-started page also wouldn't go amiss.

Why not convert this into a seed project so it can be cloned and used as a starting point for simple apps?

**Comment by evancz** [comment]
This package is not continuing into 0.17
