### ISSUE TITLE
Initial value of inputs

### ISSUE THREAD

**Issue by seanhess** [evancz/start-app#35]
I'm using elm-history, which exposes a signal `hash : Signal String`. I have wired up my app so that it runs an action when this signal changes (usually as the result of clicking a link)

I need to react to the current value of the hash when the app loads, but start-app is not sending the initial value of the signal to my application. So I'm hoping there is some way to have the input signal run an update action when the application is initialized.

Is this currently possible? Can this feature be added?

**Comment by jvoigtlaender** [comment]
See https://github.com/evancz/start-app/issues/19, in particular Evan's [comment](https://github.com/evancz/start-app/issues/19#issuecomment-130388039) there.

**Comment by seanhess** [comment]
Thank you. Do you know if it is tracked anywhere else?

**Comment by jvoigtlaender** [comment]
I don't think it is specifically tracked anywhere. It is for sure present in the collective memory of people on the mailing list. :smile: There are various threads about this issue (both in the context of `start-app` and without) on the mailing list, and for sure also several closed issues on the Elm GitHub repos. It's not something that is going to become "forgotten".

I don't know whether you have seen `foldp'`, and whether or not you are bound to using `start-app` unmodified, but just in case, [that function](http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.6.0/Signal-Extra#foldp%27) can be used to either do what you want outside the `start-app` framework or adapt a copy of `start-app` such that initial values of signals are taken into account. I'm pretty sure somebody has already done the latter, there was something on the mailing list about that a while ago.

(I also think that `foldp'` in `elm-signal-extra` is the most likely way that the "initial values problem" will eventually be resolved. When `core` gets a major overall by looking through `*-extra` packages and seeing what should be merged into `core`, that function would be considered.)

**Comment by rgrempel** [comment]
Your reference to "several closed issues on the Elm GitHub repos" triggered a thought I've been meaning to express, but haven't seen a good context for.

I think it might be worth having an explanation somewhere in an Elm GitHub repo's README of how the Elm community uses "closed" issues, because I think it's easy to misunderstand -- at least, one does see people misunderstand it from time to time.

The practice I'm referring to is this: the Elm community tends to close an issue if it's something that isn't suitable for being actively worked on right now, even if it might be taken up in the future.

I think that people sometimes misinterpret this -- that is, I think that people sometimes think that "closing" an issue means that it won't be taken up in the future. People who think this way might expect a deferred issue to remain open, but have a milestone or a label which indicates that it's being deferred to the future. (And they might expect other issues to be "assigned" or have a suitable milestone or label if they are ready for active work).

Of course, it doesn't take very long to realize what the Elm community actually means by closing an issue (i.e. we'll remember this and re-open it when it's suitable to be actively worked on). But, since Elm is a growing community, there are always newcomers who might not understand that. So, it might be a good idea to spell it out in a README somewhere. Of course, that's no guarantee that people will read it, but it might help.

**Comment by jvoigtlaender** [comment]
Maybe in https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md?

**Comment by seanhess** [comment]
I just submitted a PR with a change that fixes this. I'm hoping it can be merged!

**Comment by ccapndave** [comment]
I've also run into this issue.  It can be worked around in Javascript by passing dummy values for the ports to `Elm.embed`, and then immediately calling `send` on each port with the real default value but it would definitely be nicer if this was in the core.
