### ISSUE TITLE
Why use a Maybe?

### ISSUE THREAD

**Issue by ccorcos** [evancz/start-app#42]
In the simple app:

```elm
    address =
      Signal.forwardTo actions.address Just

    update maybeAction model =
      case maybeAction of
        Just action ->
            config.update action model

        Nothing ->
            Debug.crash "This should never happen."
```

What wrap it in a maybe?

**Comment by ccorcos** [comment]
Hmm. I see its because of a type signature issue. but when why doesnt the app crash immediately?

https://github.com/evancz/start-app/blob/master/src/StartApp/Simple.elm#L85

This seems pretty awkward/hacky to me

**Comment by rgrempel** [comment]
There are a couple of underlying issues here.

One is that the initial value of a `Signal` is a little special. For instance, `Signal.foldp` does not do anything with the initial value of a Signal. So, that is why the app doesn't crash -- the `update` method never sees the initial value. And `StartApp.Simple` arranges things so that, after the initial value, all updates get a `Just`.

However, every `Signal` does have to have an initial value. The difficulty `StartApp.Simple` faces here is that its model type is parameterized, and it doesn't ask the client to supply an initial value. So, it needs to wrap the parameterized type in a `Maybe`, so that it can have some sensible initial value to supply.

Note that the more advanced `StartApp` (without the simple) now does ask the client for an initial value, so it can avoid this technique.

**Comment by ccorcos** [comment]
I see. That just feels weird. I supposed you'd need an initial value for the compiler to do all the type checking, but it seems sensible to me that a signal wouldn't necessarily need an initial value. Perhaps its always wrapped in a maybe or something.

it looks like you you're just replacing the maybe with a list and mapping through the actions in the more advanced one.

https://github.com/evancz/start-app/blob/master/src/StartApp.elm#L100-L101

I'm new to elm so I dont exactly know what I'm doing, but I really like how this javascript library works -- I believe it was inspired by elm signals:

https://github.com/paldepind/flyd

But this library allows me to do the same exact thing in a more concise and intuitive way:

https://github.com/ccorcos/elmish/blob/master/tutorial/elmish.coffee#L15-L19

The elm way is just very confusing to me.

**Comment by ccorcos** [comment]
I see what you're saying about not worrying about the initial value of the signal...

https://github.com/elm-lang/core/blob/master/src/Native/Signal.js#L209-L231

**Comment by rgrempel** [comment]
At one time, there was some discussion about distinguishing between a `Signal` and a `Stream`, where one would represent something that always had a value (and thus an initial value), while the other would represent something more like events.

There is some code along those lines here:

http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.7.0/Signal-Stream

**Comment by rgrempel** [comment]
flyd looks very interesting ... it's amazing how many idioms Javascript can accommodate. And, amazing how much reach FRP is getting.

One difference between flyd streams and Elm signals is that flyd streams can begin and end, whereas Elm signals are infinite -- they have always existed, and will always exist.

**Comment by ccorcos** [comment]
Yeah. I never really end flyd streams, especially in my elmish example... I know what you're saying about JS though. You have more than enough rope to hang yourself, but you can bend the language to work however you want. This works for better and for worse, especially when you're forced to work with someone else's shitty code

**Comment by jvoigtlaender** [comment]
Can this issue be closed?
